// Generated by CoffeeScript 1.6.2
var greetings, hi;

(function() {
  return 'Hello, functions!';
});

console.log((function() {
  return 'Hello, functions!';
})());

hi = function() {
  return 'Hello, functions! with hi';
};

console.log(hi());

greetings = function(name) {
  return "Hello, " + name + "!";
};

console.log(greetings('Minh'));
