// Generated by CoffeeScript 1.6.2
var cube, greetings, hi, shipNameFull1, shipNameFull2, shipNameString;

(function() {
  return 'Hello, functions!';
});

console.log((function() {
  return 'Hello, functions!';
})());

console.log((function() {
  return 'Hello, functions! in parantheses';
})());

hi = function() {
  return 'Hello, functions! with hi';
};

console.log(hi());

greetings = function(name) {
  return "Hello, " + name + "!";
};

console.log(greetings('Minh'));

console.log(greetings('Katze'));

cube = function(x) {
  return Math.pow(x, 3);
};

console.log(cube(3));

shipNameString = 'Babylon';

shipNameFull1 = shipNameString + " " + 5;

shipNameFull2 = "" + shipNameString + " 5";

console.log(shipNameFull1);

console.log(shipNameFull2);

console.log(Math.round(3.1, Math.round(5.2)));

console.log(Math.round(3.1, Math.round(5.2)));

console.log(Math.round(3.1), Math.round(5.2));
